# Some Important NumPy Functions

## numpy.count_nonzero

### numpy.count_nonzero(a, axis=None, *, keepdims=False)

counts the number of non-zero values in array a

Paramters: a: array for which to count non-zeros
           axis: int or tuple, optional
           keepdims: bool, optional
           
Returns: count: int or array of int

## Examples:

In [2]:
import numpy as np

In [3]:
a = np.eye(4)

In [4]:
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [5]:
np.count_nonzero(a)

4

In [6]:
np.count_nonzero(a, axis=0)

array([1, 1, 1, 1], dtype=int64)

In [7]:
np.count_nonzero(a, axis=1)

array([1, 1, 1, 1], dtype=int64)

In [8]:
b = np.array([[0,1,0,2],
              [1,2,0,1],
              [0,0,0,1],
              [1,0,0,0]])

In [9]:
np.count_nonzero(b)

7

In [10]:
np.count_nonzero(b,axis=0)

array([2, 2, 0, 3], dtype=int64)

In [12]:
np.count_nonzero(b, axis=0, keepdims=True)

array([[2, 2, 0, 3]], dtype=int64)

In [13]:
np.count_nonzero(b,axis=0,keepdims=False)

array([2, 2, 0, 3], dtype=int64)

In [14]:
np.count_nonzero(b, axis=1, keepdims=False)

array([2, 3, 1, 1], dtype=int64)

In [15]:
np.count_nonzero(b, axis=1, keepdims=True)

array([[2],
       [3],
       [1],
       [1]], dtype=int64)

In [34]:
c = np.array([[[1,2,0],[0,1,9],[1,0,0]],
              [[0,1,1],[1,2,0],[0,0,0]],
              [[0,1,0],[0,0,0],[1,1,1]]])

In [28]:
c.shape

(3, 3, 3)

In [29]:
np.count_nonzero(c)

13

In [38]:
np.count_nonzero(c, axis=2, keepdims=True)

array([[[2],
        [2],
        [1]],

       [[2],
        [2],
        [0]],

       [[1],
        [0],
        [3]]], dtype=int64)

In [30]:
np.count_nonzero(c, axis=0,keepdims=True)

array([[[1, 3, 1],
        [1, 2, 1],
        [2, 1, 1]]], dtype=int64)

In [35]:
np.count_nonzero(c,axis=1,keepdims=True)

array([[[2, 2, 1]],

       [[1, 2, 1]],

       [[1, 2, 1]]], dtype=int64)

In [48]:
c.shape

(3, 3, 3)

In [39]:
x = np.array([1,2])

In [40]:
x.shape

(2,)

In [41]:
x = np.array([[1,2],[1,2]])

In [47]:
x

array([[1, 2],
       [1, 2]])

In [43]:
a = np.array([[[1,2],[1,2],[1,2]]])

In [44]:
a

array([[[1, 2],
        [1, 2],
        [1, 2]]])

In [45]:
a.shape

(1, 3, 2)

In [49]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
y = np.arange(100).reshape(4,5,5)

In [61]:
y

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]],

       [[75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [65]:
np.count_nonzero(y,axis=2,keepdims=True)

array([[[4],
        [5],
        [5],
        [5],
        [5]],

       [[5],
        [5],
        [5],
        [5],
        [5]],

       [[5],
        [5],
        [5],
        [5],
        [5]],

       [[5],
        [5],
        [5],
        [5],
        [5]]], dtype=int64)

In [68]:
z = np.array(
      [[[0,  1,  2,  0,  4],
        [5,  6,  7,  0,  9],
        [10, 11, 12, 0, 14],
        [0, 16, 0, 18, 19],
        [0, 21, 0, 23, 0]],

       [[0, 26, 27, 0, 29],
        [30, 0, 0, 33, 0],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 0, 44],
        [45, 0, 47, 48, 0]],

       [[50, 0, 52, 0, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 0, 0, 64],
        [65, 0, 67, 68, 69],
        [70, 71, 72, 73, 74]],

       [[75, 0, 77, 0, 79],
        [80, 0, 82, 0, 84],
        [85, 86, 0, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [69]:
array([[[2,4,4,3,3],
        [2,2,4,3,3],
        [4,3,2,3,3],
        [0,2,2,3,4],
        [4,3,4,4,2]]])

[5, 3, 4, 3, 5]

In [72]:
np.count_nonzero(z, axis=0, keepdims=True)

array([[[2, 2, 4, 0, 4],
        [4, 2, 3, 2, 3],
        [4, 4, 2, 2, 4],
        [3, 3, 3, 3, 4],
        [3, 3, 3, 4, 2]]], dtype=int64)

In [73]:
np.count_nonzero(z, axis=1, keepdims=True)

array([[[2, 5, 3, 2, 4]],

       [[4, 3, 4, 3, 3]],

       [[5, 3, 4, 3, 5]],

       [[5, 3, 4, 3, 5]]], dtype=int64)

# numpy.mean

## numpy.mean(a, axis=None, dtype=None, out=None, keepdims=<no value>, *, where=<no value>)

this function computes the arithmetic mean along the specified axis

It returns average of flattened array by default otherwise along the specified axis


Parameters--
   1. a: array
   2. axis: None or int or tuple of ints, optional
   3. dtype: data-type, optional,type to use in computing the mean, for integer inputs default is float64, for floating inputs it is same as the input dtype
   4. out: ndarray, optional
           alternate output array in which to place the result
           default is None, if provided, must have same shape as the expected output
   5. keepdims: bool, optional
                if set to True, axes which are reduced are left in the result
   6. where: array of bool, optional
   
It returns a new array containing mean values, otherwise a reference to the output array is returned

## Examples:

In [3]:
import numpy as np

In [4]:
a = np.array([[1, 2], [3, 4]])

In [5]:
np.mean(a)

2.5

In [6]:
np.mean(a, axis=0)

array([2., 3.])

In [7]:
np.mean(a, axis=1)

array([1.5, 3.5])

in single precision, mean can be inaccurate

In [8]:
a = np.zeros((2, 512*512), dtype=np.float32)

In [9]:
a

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [10]:
a[0, :] = 1.0
a[1, :] = 0.1

In [11]:
np.mean(a)

0.54999924

In [12]:
a[0, :]

array([1., 1., 1., ..., 1., 1., 1.], dtype=float32)

In [13]:
a[1, :]

array([0.1, 0.1, 0.1, ..., 0.1, 0.1, 0.1], dtype=float32)

computing the mean in float64 is accurate

In [14]:
np.mean(a, dtype=np.float64)

0.5500000007450581

specifying a where argument

In [15]:
a = np.array([[5, 9, 13], [14, 10, 12], [11, 15, 19]])
np.mean(a)

12.0

In [16]:
np.mean(a, where=[[True], [False], [False]])

9.0

In [18]:
np.mean(a, where=[[False], [True], [False]])

12.0

In [19]:
np.mean(a, where=[[False], [False], [True]])

15.0

In [36]:
np.mean(a, where=[[True], [True], [False]], dtype=np.float64, axis=0)

array([ 9.5,  9.5, 12.5])

In [21]:
a

array([[ 5,  9, 13],
       [14, 10, 12],
       [11, 15, 19]])

In [47]:
np.mean(a, out=None)

12.0

# numpy.maximum

element wise maximum of array elements

compares 2 arrays and returns new array containing the element-wise maxima

parameters:
1. x1, x2 -> array to compare
2. out -> ndarray, None or tuple of ndarray and None, optional
3. where-> array, optional

returns array or scalar

## Example

In [55]:
np.maximum([1,0,1], [1,1,2])

array([1, 1, 2])

In [59]:
np.maximum(np.eye(3),[2,3,4])

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [60]:
np.maximum([np.nan, 0, np.nan],[1,1,np.nan])

array([nan,  1., nan])

In [62]:
np.maximum(np.inf,1)

inf

In [71]:
np.maximum([1,2,4],[1,2,3], out=[np.float64,np.float64,np.float64])

TypeError: return arrays must be of ArrayType

# numpy.fmax

## numpy.fmax(x1, x2, out=None, where=True, casting='same_kind', order='k', dtype=None, subok=True[, signature, extobj])

element wise maximum of array elements

compares 2 arrays and returns new array contianing element-wise maxima. If one of the elements being compares is NaN, it returns non-NaN elements. If both elements are NaN, then first is returned. net effect is that NaNs are ignored when possible

# Examples

In [74]:
a = [1,8, 12]
b = [4, 7, 321]
max_a_b = np.fmax(a, b)
max_a_b

array([  4,   8, 321])

In [75]:
np.fmax([2, 0], [2, 4])

array([2, 4])

In [76]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [77]:
np.fmax([[2,4],[3,8]],[3,3])

array([[3, 4],
       [3, 8]])

In [79]:
np.fmax([np.nan, 0, np.nan, np.nan], [2, np.nan, 9, np.nan])

array([ 2.,  0.,  9., nan])

In [80]:
a = np.array([1, 2, np.nan])
b = np.array([3, np.nan, 4])
np.fmax(a, b)

array([3., 2., 4.])

# numpy.minimum

element wise minimum of array elements

compares 2 arrays and returns new array containing element wise minima

NaNs are propagated

In [84]:
np.minimum([2,3,4], [0, -1, 5])

array([ 0, -1,  4])

In [86]:
np.minimum([[1,2,0], [0, -2, -4]], [1,2,3])

array([[ 1,  2,  0],
       [ 0, -2, -4]])

In [90]:
np.minimum([np.nan, np.inf, np.nan],[1, np.nan, 1])

array([nan, nan, nan])

In [91]:
np.minimum(-np.inf, -3)

-inf

# numpy.zeros

## numpy.zeros(shape, dtype=float, order='C', like=None)

Return a new array of given shape and type, filled with zeros

parameters:
* shape: int or tuple of ints
* dtype: data-type, optional, default is numpy.float64
* order: {'C','F'}, optional default is 'C' ('C': row-major, 'F': column-major)

returns: array of zeros of given shape, order and dtype

## Examples

In [92]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [93]:
np.zeros((5,), dtype=int)

array([0, 0, 0, 0, 0])

In [94]:
np.zeros((2,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [98]:
np.zeros((3,), dtype=[('x', 'i4'), ('y', 'i4')])

array([(0, 0), (0, 0), (0, 0)], dtype=[('x', '<i4'), ('y', '<i4')])

In [99]:
np.zeros(2, dtype=[('x','i8'),('y','i8')])

array([(0, 0), (0, 0)], dtype=[('x', '<i8'), ('y', '<i8')])

In [107]:
np.zeros(10,dtype=[('x','f8')])

array([(0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,), (0.,),
       (0.,)], dtype=[('x', '<f8')])

# numpy.arange

# reverse vector

In [113]:
a = np.arange(0,19)

In [114]:
#reverse a
a[::-1]

array([18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,
        1,  0])

# numpy.nonzero

# numpy.eye

# numpy.random.rand

# numpy.random.randn

# numpy.random.randint