# Some Important NumPy Functions

## numpy.count_nonzero

### numpy.count_nonzero(a, axis=None, *, keepdims=False)

counts the number of non-zero values in array a

Paramters: a: array for which to count non-zeros
           axis: int or tuple, optional
           keepdims: bool, optional
           
Returns: count: int or array of int

## Examples:

In [2]:
import numpy as np

In [3]:
a = np.eye(4)

In [4]:
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [5]:
np.count_nonzero(a)

4

In [6]:
np.count_nonzero(a, axis=0)

array([1, 1, 1, 1], dtype=int64)

In [7]:
np.count_nonzero(a, axis=1)

array([1, 1, 1, 1], dtype=int64)

In [8]:
b = np.array([[0,1,0,2],
              [1,2,0,1],
              [0,0,0,1],
              [1,0,0,0]])

In [9]:
np.count_nonzero(b)

7

In [10]:
np.count_nonzero(b,axis=0)

array([2, 2, 0, 3], dtype=int64)

In [12]:
np.count_nonzero(b, axis=0, keepdims=True)

array([[2, 2, 0, 3]], dtype=int64)

In [13]:
np.count_nonzero(b,axis=0,keepdims=False)

array([2, 2, 0, 3], dtype=int64)

In [14]:
np.count_nonzero(b, axis=1, keepdims=False)

array([2, 3, 1, 1], dtype=int64)

In [15]:
np.count_nonzero(b, axis=1, keepdims=True)

array([[2],
       [3],
       [1],
       [1]], dtype=int64)

In [34]:
c = np.array([[[1,2,0],[0,1,9],[1,0,0]],
              [[0,1,1],[1,2,0],[0,0,0]],
              [[0,1,0],[0,0,0],[1,1,1]]])

In [28]:
c.shape

(3, 3, 3)

In [29]:
np.count_nonzero(c)

13

In [38]:
np.count_nonzero(c, axis=2, keepdims=True)

array([[[2],
        [2],
        [1]],

       [[2],
        [2],
        [0]],

       [[1],
        [0],
        [3]]], dtype=int64)

In [30]:
np.count_nonzero(c, axis=0,keepdims=True)

array([[[1, 3, 1],
        [1, 2, 1],
        [2, 1, 1]]], dtype=int64)

In [35]:
np.count_nonzero(c,axis=1,keepdims=True)

array([[[2, 2, 1]],

       [[1, 2, 1]],

       [[1, 2, 1]]], dtype=int64)

In [48]:
c.shape

(3, 3, 3)

In [39]:
x = np.array([1,2])

In [40]:
x.shape

(2,)

In [41]:
x = np.array([[1,2],[1,2]])

In [47]:
x

array([[1, 2],
       [1, 2]])

In [43]:
a = np.array([[[1,2],[1,2],[1,2]]])

In [44]:
a

array([[[1, 2],
        [1, 2],
        [1, 2]]])

In [45]:
a.shape

(1, 3, 2)

In [49]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
y = np.arange(100).reshape(4,5,5)

In [61]:
y

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]],

       [[75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [65]:
np.count_nonzero(y,axis=2,keepdims=True)

array([[[4],
        [5],
        [5],
        [5],
        [5]],

       [[5],
        [5],
        [5],
        [5],
        [5]],

       [[5],
        [5],
        [5],
        [5],
        [5]],

       [[5],
        [5],
        [5],
        [5],
        [5]]], dtype=int64)

In [68]:
z = np.array(
      [[[0,  1,  2,  0,  4],
        [5,  6,  7,  0,  9],
        [10, 11, 12, 0, 14],
        [0, 16, 0, 18, 19],
        [0, 21, 0, 23, 0]],

       [[0, 26, 27, 0, 29],
        [30, 0, 0, 33, 0],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 0, 44],
        [45, 0, 47, 48, 0]],

       [[50, 0, 52, 0, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 0, 0, 64],
        [65, 0, 67, 68, 69],
        [70, 71, 72, 73, 74]],

       [[75, 0, 77, 0, 79],
        [80, 0, 82, 0, 84],
        [85, 86, 0, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [69]:
array([[[2,4,4,3,3],
        [2,2,4,3,3],
        [4,3,2,3,3],
        [0,2,2,3,4],
        [4,3,4,4,2]]])

[5, 3, 4, 3, 5]

In [72]:
np.count_nonzero(z, axis=0, keepdims=True)

array([[[2, 2, 4, 0, 4],
        [4, 2, 3, 2, 3],
        [4, 4, 2, 2, 4],
        [3, 3, 3, 3, 4],
        [3, 3, 3, 4, 2]]], dtype=int64)

In [73]:
np.count_nonzero(z, axis=1, keepdims=True)

array([[[2, 5, 3, 2, 4]],

       [[4, 3, 4, 3, 3]],

       [[5, 3, 4, 3, 5]],

       [[5, 3, 4, 3, 5]]], dtype=int64)

# numpy.mean

## numpy.mean(a, axis=None, dtype=None, out=None, keepdims=<no value>, *, where=<no value>)

this function computes the arithmetic mean along the specified axis

It returns average of flattened array by default otherwise along the specified axis


Parameters--
   1. a: array
   2. axis: None or int or tuple of ints, optional
   3. dtype: data-type, optional,type to use in computing the mean, for integer inputs default is float64, for floating inputs it is same as the input dtype
   4. out: ndarray, optional
           alternate output array in which to place the result
           default is None, if provided, must have same shape as the expected output
   5. keepdims: bool, optional
                if set to True, axes which are reduced are left in the result
   6. where: array of bool, optional
   
It returns a new array containing mean values, otherwise a reference to the output array is returned

## Examples:

In [3]:
import numpy as np

In [4]:
a = np.array([[1, 2], [3, 4]])

In [5]:
np.mean(a)

2.5

In [6]:
np.mean(a, axis=0)

array([2., 3.])

In [7]:
np.mean(a, axis=1)

array([1.5, 3.5])

in single precision, mean can be inaccurate

In [8]:
a = np.zeros((2, 512*512), dtype=np.float32)

In [9]:
a

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [10]:
a[0, :] = 1.0
a[1, :] = 0.1

In [11]:
np.mean(a)

0.54999924

In [12]:
a[0, :]

array([1., 1., 1., ..., 1., 1., 1.], dtype=float32)

In [13]:
a[1, :]

array([0.1, 0.1, 0.1, ..., 0.1, 0.1, 0.1], dtype=float32)

computing the mean in float64 is accurate

In [14]:
np.mean(a, dtype=np.float64)

0.5500000007450581

specifying a where argument

In [15]:
a = np.array([[5, 9, 13], [14, 10, 12], [11, 15, 19]])
np.mean(a)

12.0

In [16]:
np.mean(a, where=[[True], [False], [False]])

9.0

In [18]:
np.mean(a, where=[[False], [True], [False]])

12.0

In [19]:
np.mean(a, where=[[False], [False], [True]])

15.0

In [36]:
np.mean(a, where=[[True], [True], [False]], dtype=np.float64, axis=0)

array([ 9.5,  9.5, 12.5])

In [21]:
a

array([[ 5,  9, 13],
       [14, 10, 12],
       [11, 15, 19]])

In [47]:
np.mean(a, out=None)

12.0