# Some Important NumPy Functions

## numpy.count_nonzero

### numpy.count_nonzero(a, axis=None, *, keepdims=False)

counts the number of non-zero values in array a

Paramters: a: array for which to count non-zeros
           axis: int or tuple, optional
           keepdims: bool, optional
           
Returns: count: int or array of int

## Examples:

In [1]:
import numpy as np

In [2]:
a = np.eye(4)

In [3]:
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [4]:
np.count_nonzero(a)

4

In [5]:
np.count_nonzero(a, axis=0)

array([1, 1, 1, 1], dtype=int64)

In [6]:
np.count_nonzero(a, axis=1)

array([1, 1, 1, 1], dtype=int64)

In [7]:
b = np.array([[0,1,0,2],
              [1,2,0,1],
              [0,0,0,1],
              [1,0,0,0]])

In [8]:
np.count_nonzero(b)

7

In [9]:
np.count_nonzero(b,axis=0)

array([2, 2, 0, 3], dtype=int64)

In [10]:
np.count_nonzero(b, axis=0, keepdims=True)

array([[2, 2, 0, 3]], dtype=int64)

In [11]:
np.count_nonzero(b,axis=0,keepdims=False)

array([2, 2, 0, 3], dtype=int64)

In [12]:
import numpy as np

In [13]:
np.count_nonzero(b, axis=1, keepdims=False)

array([2, 3, 1, 1], dtype=int64)

In [14]:
np.count_nonzero(b, axis=1, keepdims=True)

array([[2],
       [3],
       [1],
       [1]], dtype=int64)

In [15]:
c = np.array([[[1,2,0],[0,1,9],[1,0,0]],
              [[0,1,1],[1,2,0],[0,0,0]],
              [[0,1,0],[0,0,0],[1,1,1]]])

In [16]:
c.shape

(3, 3, 3)

In [17]:
np.count_nonzero(c)

13

In [18]:
np.count_nonzero(c, axis=2, keepdims=True)

array([[[2],
        [2],
        [1]],

       [[2],
        [2],
        [0]],

       [[1],
        [0],
        [3]]], dtype=int64)

In [19]:
np.count_nonzero(c, axis=0,keepdims=True)

array([[[1, 3, 1],
        [1, 2, 1],
        [2, 1, 1]]], dtype=int64)

In [20]:
np.count_nonzero(c,axis=1,keepdims=True)

array([[[2, 2, 1]],

       [[1, 2, 1]],

       [[1, 2, 1]]], dtype=int64)

In [21]:
c.shape

(3, 3, 3)

In [22]:
x = np.array([1,2])

In [23]:
x.shape

(2,)

In [24]:
x = np.array([[1,2],[1,2]])

In [25]:
x

array([[1, 2],
       [1, 2]])

In [26]:
a = np.array([[[1,2],[1,2],[1,2]]])

In [27]:
a

array([[[1, 2],
        [1, 2],
        [1, 2]]])

In [28]:
a.shape

(1, 3, 2)

In [29]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
y = np.arange(100).reshape(4,5,5)

In [31]:
y

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]],

       [[75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [32]:
np.count_nonzero(y,axis=2,keepdims=True)

array([[[4],
        [5],
        [5],
        [5],
        [5]],

       [[5],
        [5],
        [5],
        [5],
        [5]],

       [[5],
        [5],
        [5],
        [5],
        [5]],

       [[5],
        [5],
        [5],
        [5],
        [5]]], dtype=int64)

In [33]:
z = np.array(
      [[[0,  1,  2,  0,  4],
        [5,  6,  7,  0,  9],
        [10, 11, 12, 0, 14],
        [0, 16, 0, 18, 19],
        [0, 21, 0, 23, 0]],

       [[0, 26, 27, 0, 29],
        [30, 0, 0, 33, 0],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 0, 44],
        [45, 0, 47, 48, 0]],

       [[50, 0, 52, 0, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 0, 0, 64],
        [65, 0, 67, 68, 69],
        [70, 71, 72, 73, 74]],

       [[75, 0, 77, 0, 79],
        [80, 0, 82, 0, 84],
        [85, 86, 0, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [34]:
array([[[2,4,4,3,3],
        [2,2,4,3,3],
        [4,3,2,3,3],
        [0,2,2,3,4],
        [4,3,4,4,2]]])

NameError: name 'array' is not defined

In [ ]:
np.count_nonzero(z, axis=0, keepdims=True)

In [ ]:
np.count_nonzero(z, axis=1, keepdims=True)

# numpy.mean

## numpy.mean(a, axis=None, dtype=None, out=None, keepdims=<no value>, *, where=<no value>)

this function computes the arithmetic mean along the specified axis

It returns average of flattened array by default otherwise along the specified axis


Parameters--
   1. a: array
   2. axis: None or int or tuple of ints, optional
   3. dtype: data-type, optional,type to use in computing the mean, for integer inputs default is float64, for floating inputs it is same as the input dtype
   4. out: ndarray, optional
           alternate output array in which to place the result
           default is None, if provided, must have same shape as the expected output
   5. keepdims: bool, optional
                if set to True, axes which are reduced are left in the result
   6. where: array of bool, optional
   
It returns a new array containing mean values, otherwise a reference to the output array is returned

## Examples:

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1, 2], [3, 4]])

In [ ]:
np.mean(a)

In [ ]:
np.mean(a, axis=0)

In [ ]:
np.mean(a, axis=1)

in single precision, mean can be inaccurate

In [ ]:
a = np.zeros((2, 512*512), dtype=np.float32)

In [ ]:
a

In [ ]:
a[0, :] = 1.0
a[1, :] = 0.1

In [ ]:
np.mean(a)

In [ ]:
a[0, :]

In [ ]:
a[1, :]

computing the mean in float64 is accurate

In [ ]:
np.mean(a, dtype=np.float64)

specifying a where argument

In [ ]:
a = np.array([[5, 9, 13], [14, 10, 12], [11, 15, 19]])
np.mean(a)

In [ ]:
np.mean(a, where=[[True], [False], [False]])

In [ ]:
np.mean(a, where=[[False], [True], [False]])

In [ ]:
np.mean(a, where=[[False], [False], [True]])

In [ ]:
np.mean(a, where=[[True], [True], [False]], dtype=np.float64, axis=0)

In [ ]:
a

In [ ]:
np.mean(a, out=None)

# numpy.maximum

element wise maximum of array elements

compares 2 arrays and returns new array containing the element-wise maxima

parameters:
1. x1, x2 -> array to compare
2. out -> ndarray, None or tuple of ndarray and None, optional
3. where-> array, optional

returns array or scalar

## Example

In [ ]:
np.maximum([1,0,1], [1,1,2])

In [ ]:
np.maximum(np.eye(3),[2,3,4])

In [ ]:
np.maximum([np.nan, 0, np.nan],[1,1,np.nan])

In [ ]:
np.maximum(np.inf,1)

In [ ]:
np.maximum([1,2,4],[1,2,3], out=[np.float64,np.float64,np.float64])

# numpy.fmax

## numpy.fmax(x1, x2, out=None, where=True, casting='same_kind', order='k', dtype=None, subok=True[, signature, extobj])

element wise maximum of array elements

compares 2 arrays and returns new array contianing element-wise maxima. If one of the elements being compares is NaN, it returns non-NaN elements. If both elements are NaN, then first is returned. net effect is that NaNs are ignored when possible

# Examples

In [ ]:
a = [1,8, 12]
b = [4, 7, 321]
max_a_b = np.fmax(a, b)
max_a_b

In [ ]:
np.fmax([2, 0], [2, 4])

In [ ]:
np.eye(2)

In [ ]:
np.fmax([[2,4],[3,8]],[3,3])

In [ ]:
np.fmax([np.nan, 0, np.nan, np.nan], [2, np.nan, 9, np.nan])

In [ ]:
a = np.array([1, 2, np.nan])
b = np.array([3, np.nan, 4])
np.fmax(a, b)

# numpy.minimum

element wise minimum of array elements

compares 2 arrays and returns new array containing element wise minima

NaNs are propagated

In [ ]:
np.minimum([2,3,4], [0, -1, 5])

In [ ]:
np.minimum([[1,2,0], [0, -2, -4]], [1,2,3])

In [ ]:
np.minimum([np.nan, np.inf, np.nan],[1, np.nan, 1])

In [ ]:
np.minimum(-np.inf, -3)

# numpy.zeros

## numpy.zeros(shape, dtype=float, order='C', like=None)

Return a new array of given shape and type, filled with zeros

parameters:
* shape: int or tuple of ints
* dtype: data-type, optional, default is numpy.float64
* order: {'C','F'}, optional default is 'C' ('C': row-major, 'F': column-major)

returns: array of zeros of given shape, order and dtype

## Examples

In [ ]:
np.zeros(5)

In [ ]:
np.zeros((5,), dtype=int)

In [ ]:
np.zeros((2,3), dtype=int)

In [ ]:
np.zeros((3,), dtype=[('x', 'i4'), ('y', 'i4')])

In [ ]:
np.zeros(2, dtype=[('x','i8'),('y','i8')])

In [ ]:
np.zeros(10,dtype=[('x','f8')])

# numpy.arange

# reverse vector

In [ ]:
a = np.arange(0,19)

In [ ]:
#reverse a
a[::-1]

# numpy.nonzero

# numpy.eye

# numpy.random.rand

# numpy.random.randn

# numpy.random.randint

# numpy.unravel_index

numpy.unravel_index(indices, shape, order='C')

In [ ]:
import numpy as np
np.unravel_index([22,41,37], (7,6))

In [ ]:
arr = np.zeros((6,7,8))
index = np.unravel_index(335, arr.shape)
index

In [ ]:
arr = np.random.randint(0, 100, size=(2, 2, 2))
arr

In [ ]:
index = np.unravel_index(7, arr.shape)
index

In [ ]:
arr = np.random.randint(0, 100, size=(6, 7, 8))
index = np.unravel_index(100, arr.shape)
index

In [ ]:
arr.reshape(336, 1)[100]

In [ ]:
arr

# numpy.tile(A, reps)

parameters:
* A: input array
* reps: number of repitions of A along each axis

returns:
* tiled output array

## Examples

In [ ]:
import numpy as np
a = np.array([0, 1, 3, 4, 5])
np.tile(a, 2)

In [ ]:
a = np.array([[1,2,3], [4,5,6]])
np.tile(a, 3)

In [ ]:
a = np.array(['X', ' '])
np.tile(a, 8)

In [ ]:
a = np.array([['X',' '],
              [' ', 'X'],
              ['X', ' '],
              [' ', 'X'],
              ['X', ' '],
              [' ', 'X'],])
np.tile(a, 3)

In [ ]:
a = np.array([[1, 2], [3, 4]])
np.tile(a, (2,1))

In [ ]:
np.tile(a, (2,2))

In [ ]:
np.tile(a, (1,2))

In [ ]:
np.tile(a, (4,4))

### Q> Create a checkerboard 8x8 matrix using the tile function

In [ ]:
a = np.array([['X',' '],[' ', 'X']])
np.tile(a, (4,4))

# Normalize a matrix

* array divided with sum of all the elements
* array divided with max value 

In [35]:
a = np.array([[3, 4], [5,6], [7, 8]])
sum_a = np.sum(a)
a_normalize = a / sum_a
a_normalize

array([[0.09090909, 0.12121212],
       [0.15151515, 0.18181818],
       [0.21212121, 0.24242424]])

In [37]:
max_a = np.max(a)
a_max_normalize = a/max_a
a_max_normalize

array([[0.375, 0.5  ],
       [0.625, 0.75 ],
       [0.875, 1.   ]])

# Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [44]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

C:\Users\INDIA\AppData\Local\Temp\ipykernel_1700\1489744843.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

## Given a 1D array, negate all elements which are between 3 and 8, in place

In [45]:
a = np.arange(0, 10)
a[(a>3)&(a<8)] *= -1
a

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

### Given a 1D array, negate all elements which are between 30 and 80, in place

In [46]:
a = np.arange(0, 100)
a[(a>30)&(a<80)] *= -1
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30, -31, -32, -33, -34, -35, -36, -37, -38,
       -39, -40, -41, -42, -43, -44, -45, -46, -47, -48, -49, -50, -51,
       -52, -53, -54, -55, -56, -57, -58, -59, -60, -61, -62, -63, -64,
       -65, -66, -67, -68, -69, -70, -71, -72, -73, -74, -75, -76, -77,
       -78, -79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99])

### Given a 2D array, negate all elements which are between 3 and 8, in place

In [55]:
a = np.random.randint(0, 20, size=(2,20))
a[(a>3) & (a<8)] *= -1
a

array([[17, -5, -7, -7, 13, -5, -5, 19,  2, 17,  3, 16,  3,  2, -4,  2,
        -7, -7, -7, 19],
       [ 1, 17,  3, -5, -7, 10,  2, 12, 11, 14, -4, 13, 18, 17, 16, -6,
         8, -7, 19, 18]])

np.array(0) / np.array(0)

In [56]:
np.array(0) / np.array(0)

C:\Users\INDIA\AppData\Local\Temp\ipykernel_1700\873513115.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


nan

In [57]:
np.array(0) // np.array(0)

C:\Users\INDIA\AppData\Local\Temp\ipykernel_1700\2018018105.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [59]:
np.array([np.nan]).astype(float).astype(int)

C:\Users\INDIA\AppData\Local\Temp\ipykernel_1700\3806834155.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(float).astype(int)


array([-2147483648])

In [60]:
np.array([np.nan]).astype(int).astype(float)

C:\Users\INDIA\AppData\Local\Temp\ipykernel_1700\699728972.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-2.14748365e+09])

In [61]:
np.array([np.nan]).astype(int).astype(int)

C:\Users\INDIA\AppData\Local\Temp\ipykernel_1700\3341796633.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(int)


array([-2147483648])

In [62]:
Z = np.eye(2)

In [63]:
Z

array([[1., 0.],
       [0., 1.]])

In [64]:
Z ** Z

array([[1., 1.],
       [1., 1.]])

In [66]:
2 << Z >> 2

TypeError: ufunc 'left_shift' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [67]:
Z < -Z

array([[False, False],
       [False, False]])

In [68]:
Z > -Z

array([[ True, False],
       [False,  True]])

# numpy.intersect1d(a,b)

### to find the common values in 2 numpy arrays

### Example

In [77]:
a = np.random.randint(0, 100, size=(4,4))
b = np.random.randint(0, 100, size=(5,5))
print(a)
print(b)
common = np.intersect1d(a, b)
common

[[39 35 81 70]
 [16 76  9  5]
 [43 66 94 40]
 [69 58 97 72]]
[[87 23 63 69 56]
 [24 61 44 51 14]
 [65 93 85 10 58]
 [58 73 46 61 52]
 [84 72 96 48 73]]


array([58, 69, 72])

# numpy.ceil(a)

when you want to round away from zero for each array elements, use ceil function

In [78]:
a = np.array([-1.23, 0.02, 3.3, 9.0])
rounded = np.ceil(a)
rounded

array([-1.,  1.,  4.,  9.])

NameError: name 'dtype' is not defined

# numpy.sqrt(a)

In [89]:
a = np.random.randint(-10, 10, size=(4,4))
np.sqrt(a)

array([[2.82842712, 1.        ,        nan, 3.        ],
       [       nan, 2.        , 2.        , 2.        ],
       [2.64575131, 2.23606798,        nan, 1.73205081],
       [       nan, 2.64575131,        nan, 0.        ]])

In [83]:
b = np.sqrt(a)
b

C:\Users\INDIA\AppData\Local\Temp\ipykernel_1700\3072016282.py:1: RuntimeWarning: invalid value encountered in sqrt
  b = np.sqrt(a)


array([[       nan, 2.23606798,        nan,        nan],
       [2.64575131,        nan,        nan,        nan],
       [       nan, 2.23606798, 2.44948974,        nan],
       [1.73205081,        nan,        nan, 1.41421356]])

# numpy.seterr(all='ignore')

## used to ignore all the warnings(not recommended)

In [86]:
b = np.sqrt(a)
np.seterr(all='ignore')
b
# no warnings generated

array([[       nan, 2.23606798,        nan,        nan],
       [2.64575131,        nan,        nan,        nan],
       [       nan, 2.23606798, 2.44948974,        nan],
       [1.73205081,        nan,        nan, 1.41421356]])

# numpy.emath.sqrt(a)

it returns square root of a elementwise
for negative values, it will return complex values
where np.sqrt returns nan for -ve values

In [88]:
a = np. random.randint(-10, 10, size=(2,2))
print(np.sqrt(a))
print(np.emath.sqrt(a))

[[2.23606798 1.41421356]
 [       nan        nan]]
[[2.23606798+0.j         1.41421356+0.j        ]
 [0.        +1.41421356j 0.        +3.16227766j]]


# Get the dates

In [97]:
import datetime as dt
today = dt.date.today()
yesterday = today - dt.timedelta(days=1)
today = np.array([today])
yesterday = np.array([yesterday])
print(today)
print(yesterday)

[datetime.date(2023, 4, 4)]
[datetime.date(2023, 4, 3)]


# get all the dates of april, 2023

In [3]:
import datetime as dt
import numpy as np
start_date = dt.date(2023, 1, 1)
num_days = 30
dates = [start_date + dt.timedelta(days=i) for i in range(num_days)]
np.array(dates)

array([datetime.date(2023, 1, 1), datetime.date(2023, 1, 2),
       datetime.date(2023, 1, 3), datetime.date(2023, 1, 4),
       datetime.date(2023, 1, 5), datetime.date(2023, 1, 6),
       datetime.date(2023, 1, 7), datetime.date(2023, 1, 8),
       datetime.date(2023, 1, 9), datetime.date(2023, 1, 10),
       datetime.date(2023, 1, 11), datetime.date(2023, 1, 12),
       datetime.date(2023, 1, 13), datetime.date(2023, 1, 14),
       datetime.date(2023, 1, 15), datetime.date(2023, 1, 16),
       datetime.date(2023, 1, 17), datetime.date(2023, 1, 18),
       datetime.date(2023, 1, 19), datetime.date(2023, 1, 20),
       datetime.date(2023, 1, 21), datetime.date(2023, 1, 22),
       datetime.date(2023, 1, 23), datetime.date(2023, 1, 24),
       datetime.date(2023, 1, 25), datetime.date(2023, 1, 26),
       datetime.date(2023, 1, 27), datetime.date(2023, 1, 28),
       datetime.date(2023, 1, 29), datetime.date(2023, 1, 30)],
      dtype=object)

## get all the dates of January, 2011

In [5]:
import datetime as dt
import numpy as np
start_date = dt.date(2011, 1, 1)
num_days = 31
dates = [start_date + dt.timedelta(days=i) for i in range(num_days)]
np.array(dates)

array([datetime.date(2011, 1, 1), datetime.date(2011, 1, 2),
       datetime.date(2011, 1, 3), datetime.date(2011, 1, 4),
       datetime.date(2011, 1, 5), datetime.date(2011, 1, 6),
       datetime.date(2011, 1, 7), datetime.date(2011, 1, 8),
       datetime.date(2011, 1, 9), datetime.date(2011, 1, 10),
       datetime.date(2011, 1, 11), datetime.date(2011, 1, 12),
       datetime.date(2011, 1, 13), datetime.date(2011, 1, 14),
       datetime.date(2011, 1, 15), datetime.date(2011, 1, 16),
       datetime.date(2011, 1, 17), datetime.date(2011, 1, 18),
       datetime.date(2011, 1, 19), datetime.date(2011, 1, 20),
       datetime.date(2011, 1, 21), datetime.date(2011, 1, 22),
       datetime.date(2011, 1, 23), datetime.date(2011, 1, 24),
       datetime.date(2011, 1, 25), datetime.date(2011, 1, 26),
       datetime.date(2011, 1, 27), datetime.date(2011, 1, 28),
       datetime.date(2011, 1, 29), datetime.date(2011, 1, 30),
       datetime.date(2011, 1, 31)], dtype=object)