In [1]:
w1,w2,w3 = 0.3,0.2,0.5

In [2]:
kanto_temp = 73
kanto_rainfall = 67
kanto_humidity = 43

In [3]:
kanto_yeild_apples = kanto_temp*w1 + kanto_rainfall*w2 + kanto_humidity*w3
kanto_yeild_apples

56.8

In [4]:
print("the exepected yeild of apples in kanto region is {} tons per hectare.".format(kanto_yeild_apples))

the exepected yeild of apples in kanto region is 56.8 tons per hectare.


In [5]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

In [6]:
weights = [w1, w2, w3]

In [7]:
def crop_yeild(region, weights):
    result = 0
    for x, w in zip(region, weights):
        result += x * w
    return result

In [8]:
crop_yeild(kanto, weights)

56.8

In [9]:
crop_yeild(johto, weights)

76.9

In [10]:
crop_yeild(hoenn, weights)

81.9

In [11]:

(crop_yeild(sinnoh, weights))

57.699999999999996

In [12]:
crop_yeild(unova, weights)

74.9

# Going from Python lists to Numpy arrays

In [13]:
!pip install numpy --upgrade --quiet --user

In [14]:
import numpy as np

In [15]:
kanto = np.array([73, 67, 43])

In [16]:
kanto

array([73, 67, 43])

In [17]:
type (kanto)

numpy.ndarray

In [18]:
weights = np.array([w1,w2,w3])

In [19]:
weights

array([0.3, 0.2, 0.5])

In [20]:
type(weights)

numpy.ndarray

In [21]:
weights[0]

0.3

In [22]:
weights[1]

0.2

In [23]:
weights[2]

0.5

In [24]:
kanto[0]

73

In [25]:
kanto[1]

67

In [26]:
kanto[2]

43

Operating on Numpy arrays

In [27]:
np.dot(kanto,weights)

56.8

In [28]:
np.dot(johto,weights)

76.9

In [29]:
johto

[91, 88, 64]

In [30]:
type(johto)

list

In [31]:
johto = np.array(johto)

In [32]:
johto

array([91, 88, 64])

In [33]:
type(johto)

numpy.ndarray

In [34]:
np.dot(johto,weights)

76.9

In [35]:
(kanto*weights).sum()

56.8

In [36]:
(johto*weights).sum()

76.9

In [37]:
a = [1,2,3]
b = [7,8,9]
a = np.array(a)
b = np.array(b)
np.dot(a,b)

50

In [38]:
(a*b).sum()

50

In [39]:
x = a*b

In [40]:
x

array([ 7, 16, 27])

In [41]:
x.sum()

50

In [42]:
arr1 = list(range(1000000))
arr2 = list(range(1000000,2000000))
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [43]:
arr1_np

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [44]:
arr2_np

array([1000000, 1000001, 1000002, ..., 1999997, 1999998, 1999999])

In [45]:
%%time
result = 0
for x1,x2 in zip(arr1,arr2):
    result += x1*x2
result

Wall time: 1.65 s


833332333333500000

In [46]:
x = (arr1_np*arr2_np).sum()
x

-1942957984

In [47]:
%%time
np.dot(arr1_np, arr2_np)

Wall time: 4 ms


-1942957984

In [48]:
# Python lists
arr1 = list(range(1000000))
arr2 = list(range(1000000, 2000000))

# Numpy arrays
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [49]:
%%time
np.dot(arr1_np, arr2_np)

Wall time: 9.99 ms


-1942957984

In [50]:
import numpy as np

In [51]:
a = list(range(10))
b = list(range(10,20))

In [52]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [53]:
b

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [54]:
a_np = np.array(a)
b_np = np.array(b)

In [55]:
a_np

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
b_np

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [57]:
%%time
np.dot(a_np,b_np)

Wall time: 0 ns


735

In [59]:
%%time
result=0
for x, y in zip(a, b):
    result += x*y
result

Wall time: 0 ns


735

In [60]:
a = list(range(100))
b = list(range(100,200))

In [61]:
a_np = np.array(a)
b_np = np.array(b)

In [62]:
%%time
result = 0
for x, y in zip(a, b):
    result+=x*y
result

Wall time: 0 ns


823350

In [63]:
%%time
np.dot(a_np,b_np)

Wall time: 0 ns


823350

In [64]:
a = list(range(1000))
b=list(range(1000,2000))
a_np = np.array(a)
b_np = np.array(b)

In [65]:
%%time
result=0
for x, y in zip(a, b):
    result+=x*y
result

Wall time: 1 ms


832333500

In [66]:
%%time
np.dot(a_np, b_np)

Wall time: 0 ns


832333500

In [86]:
a = list(range(10000))
b = list(range(10000,20000))
a_np = np.array(a,dtype=np.int64)
b_np = np.array(b,dtype=np.int64)

In [87]:
%%time
result=0
for x,y in zip(a,b):
    result+= x*y
result

Wall time: 7 ms


833233335000

In [88]:
%%time
np.dot(a_np, b_np)

Wall time: 1.01 ms


833233335000

In [75]:
a_np

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [76]:
b_np

array([10000, 10001, 10002, ..., 19997, 19998, 19999])

In [83]:
# Python lists
arr3 = list(range(1000000))
arr4 = list(range(1000000, 2000000))

# Numpy arrays
arr3_np = np.array(arr3,dtype=np.int64)
arr4_np = np.array(arr4,dtype=np.int64)

In [84]:
%%time
result = 0
for x1, x2 in zip(arr3, arr4):
    result += x1 * x2
result

Wall time: 337 ms


833332333333500000

In [85]:
%%time
np.dot(arr3_np, arr4_np)

Wall time: 1.98 ms


833332333333500000

In [89]:
import sha827

ModuleNotFoundError: No module named 'sha827'