In [1]:
w1,w2,w3 = 0.3,0.2,0.5

In [2]:
kanto_temp = 73
kanto_rainfall = 67
kanto_humidity = 43

In [3]:
kanto_yeild_apples = kanto_temp*w1 + kanto_rainfall*w2 + kanto_humidity*w3
kanto_yeild_apples

56.8

In [4]:
print("the exepected yeild of apples in kanto region is {} tons per hectare.".format(kanto_yeild_apples))

the exepected yeild of apples in kanto region is 56.8 tons per hectare.


In [5]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

In [6]:
weights = [w1, w2, w3]

In [7]:
def crop_yeild(region, weights):
    result = 0
    for x, w in zip(region, weights):
        result += x * w
    return result

In [8]:
crop_yeild(kanto, weights)

56.8

In [9]:
crop_yeild(johto, weights)

76.9

In [10]:
crop_yeild(hoenn, weights)

81.9

In [11]:

(crop_yeild(sinnoh, weights))

57.699999999999996

In [12]:
crop_yeild(unova, weights)

74.9

# Going from Python lists to Numpy arrays

In [13]:
!pip install numpy --upgrade --quiet --user

In [14]:
import numpy as np

In [15]:
kanto = np.array([73, 67, 43])

In [16]:
kanto

array([73, 67, 43])

In [17]:
type (kanto)

numpy.ndarray

In [18]:
weights = np.array([w1,w2,w3])

In [19]:
weights

array([0.3, 0.2, 0.5])

In [20]:
type(weights)

numpy.ndarray

In [21]:
weights[0]

0.3

In [22]:
weights[1]

0.2

In [23]:
weights[2]

0.5

In [24]:
kanto[0]

73

In [25]:
kanto[1]

67

In [26]:
kanto[2]

43

Operating on Numpy arrays

In [27]:
np.dot(kanto,weights)

56.8

In [28]:
np.dot(johto,weights)

76.9

In [29]:
johto

[91, 88, 64]

In [30]:
type(johto)

list

In [31]:
johto = np.array(johto)

In [32]:
johto

array([91, 88, 64])

In [33]:
type(johto)

numpy.ndarray

In [34]:
np.dot(johto,weights)

76.9

In [35]:
(kanto*weights).sum()

56.8

In [36]:
(johto*weights).sum()

76.9

In [37]:
a = [1,2,3]
b = [7,8,9]
a = np.array(a)
b = np.array(b)
np.dot(a,b)

50

In [38]:
(a*b).sum()

50

In [39]:
x = a*b

In [40]:
x

array([ 7, 16, 27])

In [41]:
x.sum()

50

In [42]:
arr1 = list(range(1000000))
arr2 = list(range(1000000,2000000))
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [43]:
arr1_np

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [44]:
arr2_np

array([1000000, 1000001, 1000002, ..., 1999997, 1999998, 1999999])

In [45]:
%%time
result = 0
for x1,x2 in zip(arr1,arr2):
    result += x1*x2
result

Wall time: 1.65 s


833332333333500000

In [46]:
x = (arr1_np*arr2_np).sum()
x

-1942957984

In [47]:
%%time
np.dot(arr1_np, arr2_np)

Wall time: 4 ms


-1942957984

In [48]:
# Python lists
arr1 = list(range(1000000))
arr2 = list(range(1000000, 2000000))

# Numpy arrays
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [49]:
%%time
np.dot(arr1_np, arr2_np)

Wall time: 9.99 ms


-1942957984

In [50]:
import numpy as np

In [51]:
a = list(range(10))
b = list(range(10,20))

In [52]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [53]:
b

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [54]:
a_np = np.array(a)
b_np = np.array(b)

In [55]:
a_np

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
b_np

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [57]:
%%time
np.dot(a_np,b_np)

Wall time: 0 ns


735

In [59]:
%%time
result=0
for x, y in zip(a, b):
    result += x*y
result

Wall time: 0 ns


735

In [60]:
a = list(range(100))
b = list(range(100,200))

In [61]:
a_np = np.array(a)
b_np = np.array(b)

In [62]:
%%time
result = 0
for x, y in zip(a, b):
    result+=x*y
result

Wall time: 0 ns


823350

In [63]:
%%time
np.dot(a_np,b_np)

Wall time: 0 ns


823350

In [64]:
a = list(range(1000))
b=list(range(1000,2000))
a_np = np.array(a)
b_np = np.array(b)

In [65]:
%%time
result=0
for x, y in zip(a, b):
    result+=x*y
result

Wall time: 1 ms


832333500

In [66]:
%%time
np.dot(a_np, b_np)

Wall time: 0 ns


832333500

In [86]:
a = list(range(10000))
b = list(range(10000,20000))
a_np = np.array(a,dtype=np.int64)
b_np = np.array(b,dtype=np.int64)

In [87]:
%%time
result=0
for x,y in zip(a,b):
    result+= x*y
result

Wall time: 7 ms


833233335000

In [88]:
%%time
np.dot(a_np, b_np)

Wall time: 1.01 ms


833233335000

In [75]:
a_np

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [76]:
b_np

array([10000, 10001, 10002, ..., 19997, 19998, 19999])

In [83]:
# Python lists
arr3 = list(range(1000000))
arr4 = list(range(1000000, 2000000))

# Numpy arrays
arr3_np = np.array(arr3,dtype=np.int64)
arr4_np = np.array(arr4,dtype=np.int64)

In [84]:
%%time
result = 0
for x1, x2 in zip(arr3, arr4):
    result += x1 * x2
result

Wall time: 337 ms


833332333333500000

In [85]:
%%time
np.dot(arr3_np, arr4_np)

Wall time: 1.98 ms


833332333333500000

# Multi-dimensional Numpy arrays

In [90]:
climate_data = np.array([
    [73, 67, 43],
    [91, 88, 64],
    [87, 134, 58],
    [102, 43, 37],
    [69, 96, 70]
])

In [91]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [92]:
#2d array matrix
climate_data.shape

(5, 3)

In [93]:
weights

array([0.3, 0.2, 0.5])

In [94]:
#1D array vector
weights.shape

(3,)

In [95]:
#3D array
arr3 = np.array([
    [
        [11, 12, 13],
        [13, 14, 15]
    ],
    [
        [15, 16, 17],
        [17, 18, 19]
    ]
])

In [96]:
arr3.shape

(2, 2, 3)

In [97]:
weights.dtype

dtype('float64')

In [98]:
arr3.dtype

dtype('int32')

In [104]:
arr4 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12.1]
    ]
])

In [105]:
arr4.dtype

dtype('float64')

In [106]:
arr4

array([[[ 1. ,  2. ,  3. ],
        [ 4. ,  5. ,  6. ]],

       [[ 7. ,  8. ,  9. ],
        [10. , 11. , 12.1]]])

In [107]:
np.matmul(climate_data, weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [108]:
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [109]:
import urllib.request
urllib.request.urlretrieve('https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x25e02eb30a0>)

In [111]:
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)

In [112]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [113]:
climate_data.shape

(10000, 3)

In [114]:
weights = np.array([0.3, 0.2, 0.5])

In [116]:
yeilds = climate_data @ weights

In [117]:
yeilds

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [118]:
yeilds.shape

(10000,)

concatenate yeilds in climate_data file at 4th column

In [119]:
climate_results = np.concatenate((climate_data, yeilds.reshape(10000, 1)), axis = 1)

In [121]:
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [122]:
weights2 = np.array([0.5, 1.3, 9.2])

In [126]:
yeilds2 = climate_data @ weights2

In [127]:
yeilds2.shape

(10000,)

In [128]:
yeilds2.reshape(10000, 1)

array([[1022.1],
       [ 748. ],
       [ 796.4],
       ...,
       [ 663.7],
       [ 964.5],
       [ 795.9]])

In [131]:
climate_results = np.concatenate((climate_results, yeilds2.reshape(10000, 1)), axis=1)

In [132]:
climate_results

array([[  25. ,   76. ,   99. , 1022.1, 1022.1],
       [  39. ,   65. ,   70. ,  748. ,  748. ],
       [  59. ,   45. ,   77. ,  796.4,  796.4],
       ...,
       [  99. ,   62. ,   58. ,  663.7,  663.7],
       [  70. ,   71. ,   91. ,  964.5,  964.5],
       [  92. ,   39. ,   76. ,  795.9,  795.9]])

In [133]:
weights3 = np.array([12, 13, 14])

In [134]:
yeilds3 = climate_data @ weights3

In [135]:
yeilds3

array([2674., 2293., 2371., ..., 2806., 3037., 2675.])

In [136]:
yeilds3_reshaped = yeilds3.reshape(10000, 1)

In [137]:
climate_results = np.concatenate((climate_results, yeilds3_reshaped), axis=1)

In [139]:
climate_results

array([[  25. ,   76. ,   99. , 1022.1, 1022.1, 2674. ],
       [  39. ,   65. ,   70. ,  748. ,  748. , 2293. ],
       [  59. ,   45. ,   77. ,  796.4,  796.4, 2371. ],
       ...,
       [  99. ,   62. ,   58. ,  663.7,  663.7, 2806. ],
       [  70. ,   71. ,   91. ,  964.5,  964.5, 3037. ],
       [  92. ,   39. ,   76. ,  795.9,  795.9, 2675. ]])

save the data in file

In [143]:
np.savetxt('climate_results.txt',
          climate_results,
          fmt='%.2f',
          delimiter='  ,  ',
          header='temperature, rainfall, humidity, yeild1, yeild2, yeild3',
          comments='')

## Arithmetic operations, broadcasting and comparison

In [2]:
import numpy as np

In [3]:
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,1,2,3]])

In [4]:
arr3 = np.array([[11,12,13,14],
                 [15,16,17,18],
                 [19,11,12,13]])

In [5]:
#adding a scalar
arr2 + 2

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11,  3,  4,  5]])

In [7]:
arr3 + (-20)

array([[-9, -8, -7, -6],
       [-5, -4, -3, -2],
       [-1, -9, -8, -7]])

In [8]:
arr3

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 11, 12, 13]])

In [9]:
arr2+arr3

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 12, 14, 16]])

In [10]:
arr3-arr3

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [11]:
arr2-arr3

array([[-10, -10, -10, -10],
       [-10, -10, -10, -10],
       [-10, -10, -10, -10]])

In [12]:
arr3-arr2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [13]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 2, 3]])

In [14]:
arr3

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 11, 12, 13]])

In [15]:
arr2/2 - arr3/3

array([[-3.16666667, -3.        , -2.83333333, -2.66666667],
       [-2.5       , -2.33333333, -2.16666667, -2.        ],
       [-1.83333333, -3.16666667, -3.        , -2.83333333]])

In [16]:
arr2*arr3

array([[ 11,  24,  39,  56],
       [ 75,  96, 119, 144],
       [171,  11,  24,  39]])

In [17]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 2, 3]])

In [18]:
arr2 % 2

array([[1, 0, 1, 0],
       [1, 0, 1, 0],
       [1, 1, 0, 1]], dtype=int32)

In [19]:
arr2 % 3

array([[1, 2, 0, 1],
       [2, 0, 1, 2],
       [0, 1, 2, 0]], dtype=int32)

In [20]:
arr2 // 2

array([[0, 1, 1, 2],
       [2, 3, 3, 4],
       [4, 0, 1, 1]], dtype=int32)

In [21]:
import math

In [22]:
math.ceil(arr2/2)

TypeError: only size-1 arrays can be converted to Python scalars

## array broadcasting

numpy arrays also support broadcasting, allowing arithmetic operations between 2 array with diff numbers of dimensions but compatible shapes

In [23]:
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,1,2,3]])

In [24]:
arr2.shape

(3, 4)

In [31]:
arr4 = np.array([4,5,6,7])

In [32]:
arr4.shape

(4,)

In [33]:
arr2 + arr4

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

In [34]:
arr2*arr4

array([[ 4, 10, 18, 28],
       [20, 30, 42, 56],
       [36,  5, 12, 21]])

In [35]:
arr2/arr4

array([[0.25      , 0.4       , 0.5       , 0.57142857],
       [1.25      , 1.2       , 1.16666667, 1.14285714],
       [2.25      , 0.2       , 0.33333333, 0.42857143]])

In [36]:
arr3/arr2

array([[11.        ,  6.        ,  4.33333333,  3.5       ],
       [ 3.        ,  2.66666667,  2.42857143,  2.25      ],
       [ 2.11111111, 11.        ,  6.        ,  4.33333333]])

In [37]:
arr4/arr2

array([[4.        , 2.5       , 2.        , 1.75      ],
       [0.8       , 0.83333333, 0.85714286, 0.875     ],
       [0.44444444, 5.        , 3.        , 2.33333333]])

In [40]:
a = np.array([0,1,2])
b = np.array([5])
c = np.array([5,5,5])

In [41]:
a+b

array([5, 6, 7])

In [42]:
a+c

array([5, 6, 7])

In [43]:
a.shape

(3,)

In [44]:
b.shape

(1,)

In [45]:
c.shape

(3,)

In [46]:
np.arange(3)

array([0, 1, 2])

In [47]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
np.arange(10000)

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [56]:
%%time
np.arange(1000000000, dtype=np.int64)

Wall time: 43.2 s


array([        0,         1,         2, ..., 999999997, 999999998,
       999999999], dtype=int64)

In [57]:
np.arange(100)+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199])

In [70]:
np.arange(5)+50000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

array([50000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
       50000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001,
       50000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002,
       50000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003,
       50000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004],
      dtype=object)

In [76]:
np.arange(5)+[[1,2,3,4,5],[6,7,8,9,1]]

array([[ 1,  3,  5,  7,  9],
       [ 6,  8, 10, 12,  5]])

In [74]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [77]:
np.ones(0)

array([], dtype=float64)

In [78]:
np.ones(1)

array([1.])

In [94]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [95]:
np.ones((3,3))+np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [100]:
np.ones((5,1)) + np.arange(5)

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [101]:
np.arange(5).shape

(5,)

In [102]:
np.ones((5,1)).shape

(5, 1)

In [109]:
sh = (3,1)
x = np.ones(sh)
x

array([[1.],
       [1.],
       [1.]])

In [107]:
x + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [110]:
arr5 = np.array([7,8])

In [111]:
arr5

array([7, 8])

In [112]:
arr5.shape

(2,)

In [113]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 2, 3]])

In [115]:
arr2.shape

(3, 4)

In [124]:
y = arr2.reshape(6,2)

In [125]:
arr5

array([7, 8])

In [126]:
y

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [9, 1],
       [2, 3]])

In [127]:
y + arr5

array([[ 8, 10],
       [10, 12],
       [12, 14],
       [14, 16],
       [16,  9],
       [ 9, 11]])

## Array comparison

In [128]:
arr1 = np.array([[1,2,3],[3,4,5]])
arr2 = np.array([[2,2,3],[1,2,5]])

In [129]:
arr1 == arr2

array([[False,  True,  True],
       [False, False,  True]])

In [130]:
arr1 != arr2

array([[ True, False, False],
       [ True,  True, False]])

In [131]:
arr1 >= arr2

array([[False,  True,  True],
       [ True,  True,  True]])

In [132]:
arr1 < arr2

array([[ True, False, False],
       [False, False, False]])

In [133]:
(arr1 == arr2).sum()

3