In [1]:
w1,w2,w3 = 0.3,0.2,0.5

In [2]:
kanto_temp = 73
kanto_rainfall = 67
kanto_humidity = 43

In [3]:
kanto_yeild_apples = kanto_temp*w1 + kanto_rainfall*w2 + kanto_humidity*w3
kanto_yeild_apples

56.8

In [4]:
print("the exepected yeild of apples in kanto region is {} tons per hectare.".format(kanto_yeild_apples))

the exepected yeild of apples in kanto region is 56.8 tons per hectare.


In [5]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

In [6]:
weights = [w1, w2, w3]

In [7]:
def crop_yeild(region, weights):
    result = 0
    for x, w in zip(region, weights):
        result += x * w
    return result

In [8]:
crop_yeild(kanto, weights)

56.8

In [9]:
crop_yeild(johto, weights)

76.9

In [10]:
crop_yeild(hoenn, weights)

81.9

In [11]:

(crop_yeild(sinnoh, weights))

57.699999999999996

In [12]:
crop_yeild(unova, weights)

74.9

# Going from Python lists to Numpy arrays

In [13]:
!pip install numpy --upgrade --quiet --user

In [14]:
import numpy as np

In [15]:
kanto = np.array([73, 67, 43])

In [16]:
kanto

array([73, 67, 43])

In [17]:
type (kanto)

numpy.ndarray

In [18]:
weights = np.array([w1,w2,w3])

In [19]:
weights

array([0.3, 0.2, 0.5])

In [20]:
type(weights)

numpy.ndarray

In [21]:
weights[0]

0.3

In [22]:
weights[1]

0.2

In [23]:
weights[2]

0.5

In [24]:
kanto[0]

73

In [25]:
kanto[1]

67

In [26]:
kanto[2]

43

Operating on Numpy arrays

In [27]:
np.dot(kanto,weights)

56.8

In [28]:
np.dot(johto,weights)

76.9

In [29]:
johto

[91, 88, 64]

In [30]:
type(johto)

list

In [31]:
johto = np.array(johto)

In [32]:
johto

array([91, 88, 64])

In [33]:
type(johto)

numpy.ndarray

In [34]:
np.dot(johto,weights)

76.9

In [35]:
(kanto*weights).sum()

56.8

In [36]:
(johto*weights).sum()

76.9

In [37]:
a = [1,2,3]
b = [7,8,9]
a = np.array(a)
b = np.array(b)
np.dot(a,b)

50

In [38]:
(a*b).sum()

50

In [39]:
x = a*b

In [40]:
x

array([ 7, 16, 27])

In [41]:
x.sum()

50

In [42]:
arr1 = list(range(1000000))
arr2 = list(range(1000000,2000000))
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [43]:
arr1_np

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [44]:
arr2_np

array([1000000, 1000001, 1000002, ..., 1999997, 1999998, 1999999])

In [45]:
%%time
result = 0
for x1,x2 in zip(arr1,arr2):
    result += x1*x2
result

Wall time: 1.65 s


833332333333500000

In [46]:
x = (arr1_np*arr2_np).sum()
x

-1942957984

In [47]:
%%time
np.dot(arr1_np, arr2_np)

Wall time: 4 ms


-1942957984

In [48]:
# Python lists
arr1 = list(range(1000000))
arr2 = list(range(1000000, 2000000))

# Numpy arrays
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [49]:
%%time
np.dot(arr1_np, arr2_np)

Wall time: 9.99 ms


-1942957984

In [50]:
import numpy as np

In [51]:
a = list(range(10))
b = list(range(10,20))

In [52]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [53]:
b

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [54]:
a_np = np.array(a)
b_np = np.array(b)

In [55]:
a_np

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
b_np

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [57]:
%%time
np.dot(a_np,b_np)

Wall time: 0 ns


735

In [59]:
%%time
result=0
for x, y in zip(a, b):
    result += x*y
result

Wall time: 0 ns


735

In [60]:
a = list(range(100))
b = list(range(100,200))

In [61]:
a_np = np.array(a)
b_np = np.array(b)

In [62]:
%%time
result = 0
for x, y in zip(a, b):
    result+=x*y
result

Wall time: 0 ns


823350

In [63]:
%%time
np.dot(a_np,b_np)

Wall time: 0 ns


823350

In [64]:
a = list(range(1000))
b=list(range(1000,2000))
a_np = np.array(a)
b_np = np.array(b)

In [65]:
%%time
result=0
for x, y in zip(a, b):
    result+=x*y
result

Wall time: 1 ms


832333500

In [66]:
%%time
np.dot(a_np, b_np)

Wall time: 0 ns


832333500

In [86]:
a = list(range(10000))
b = list(range(10000,20000))
a_np = np.array(a,dtype=np.int64)
b_np = np.array(b,dtype=np.int64)

In [87]:
%%time
result=0
for x,y in zip(a,b):
    result+= x*y
result

Wall time: 7 ms


833233335000

In [88]:
%%time
np.dot(a_np, b_np)

Wall time: 1.01 ms


833233335000

In [75]:
a_np

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [76]:
b_np

array([10000, 10001, 10002, ..., 19997, 19998, 19999])

In [83]:
# Python lists
arr3 = list(range(1000000))
arr4 = list(range(1000000, 2000000))

# Numpy arrays
arr3_np = np.array(arr3,dtype=np.int64)
arr4_np = np.array(arr4,dtype=np.int64)

In [84]:
%%time
result = 0
for x1, x2 in zip(arr3, arr4):
    result += x1 * x2
result

Wall time: 337 ms


833332333333500000

In [85]:
%%time
np.dot(arr3_np, arr4_np)

Wall time: 1.98 ms


833332333333500000

# Multi-dimensional Numpy arrays

In [90]:
climate_data = np.array([
    [73, 67, 43],
    [91, 88, 64],
    [87, 134, 58],
    [102, 43, 37],
    [69, 96, 70]
])

In [91]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [92]:
#2d array matrix
climate_data.shape

(5, 3)

In [93]:
weights

array([0.3, 0.2, 0.5])

In [94]:
#1D array vector
weights.shape

(3,)

In [95]:
#3D array
arr3 = np.array([
    [
        [11, 12, 13],
        [13, 14, 15]
    ],
    [
        [15, 16, 17],
        [17, 18, 19]
    ]
])

In [96]:
arr3.shape

(2, 2, 3)

In [97]:
weights.dtype

dtype('float64')

In [98]:
arr3.dtype

dtype('int32')

In [104]:
arr4 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12.1]
    ]
])

In [105]:
arr4.dtype

dtype('float64')

In [106]:
arr4

array([[[ 1. ,  2. ,  3. ],
        [ 4. ,  5. ,  6. ]],

       [[ 7. ,  8. ,  9. ],
        [10. , 11. , 12.1]]])

In [107]:
np.matmul(climate_data, weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [108]:
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [109]:
import urllib.request
urllib.request.urlretrieve('https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x25e02eb30a0>)

In [111]:
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)

In [112]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [113]:
climate_data.shape

(10000, 3)

In [114]:
weights = np.array([0.3, 0.2, 0.5])

In [116]:
yeilds = climate_data @ weights

In [117]:
yeilds

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [118]:
yeilds.shape

(10000,)

concatenate yeilds in climate_data file at 4th column

In [119]:
climate_results = np.concatenate((climate_data, yeilds.reshape(10000, 1)), axis = 1)

In [121]:
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [122]:
weights2 = np.array([0.5, 1.3, 9.2])

In [126]:
yeilds2 = climate_data @ weights2

In [127]:
yeilds2.shape

(10000,)

In [128]:
yeilds2.reshape(10000, 1)

array([[1022.1],
       [ 748. ],
       [ 796.4],
       ...,
       [ 663.7],
       [ 964.5],
       [ 795.9]])

In [131]:
climate_results = np.concatenate((climate_results, yeilds2.reshape(10000, 1)), axis=1)

In [132]:
climate_results

array([[  25. ,   76. ,   99. , 1022.1, 1022.1],
       [  39. ,   65. ,   70. ,  748. ,  748. ],
       [  59. ,   45. ,   77. ,  796.4,  796.4],
       ...,
       [  99. ,   62. ,   58. ,  663.7,  663.7],
       [  70. ,   71. ,   91. ,  964.5,  964.5],
       [  92. ,   39. ,   76. ,  795.9,  795.9]])

In [133]:
weights3 = np.array([12, 13, 14])

In [134]:
yeilds3 = climate_data @ weights3

In [135]:
yeilds3

array([2674., 2293., 2371., ..., 2806., 3037., 2675.])

In [136]:
yeilds3_reshaped = yeilds3.reshape(10000, 1)

In [137]:
climate_results = np.concatenate((climate_results, yeilds3_reshaped), axis=1)

In [139]:
climate_results

array([[  25. ,   76. ,   99. , 1022.1, 1022.1, 2674. ],
       [  39. ,   65. ,   70. ,  748. ,  748. , 2293. ],
       [  59. ,   45. ,   77. ,  796.4,  796.4, 2371. ],
       ...,
       [  99. ,   62. ,   58. ,  663.7,  663.7, 2806. ],
       [  70. ,   71. ,   91. ,  964.5,  964.5, 3037. ],
       [  92. ,   39. ,   76. ,  795.9,  795.9, 2675. ]])

save the data in file

In [143]:
np.savetxt('climate_results.txt',
          climate_results,
          fmt='%.2f',
          delimiter='  ,  ',
          header='temperature, rainfall, humidity, yeild1, yeild2, yeild3',
          comments='')